import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Navbar from "@/components/navbar";
import SplashScreen from "@/components/splash-screen";
import { TransitionProvider } from "@/context/TransitionContext";
import Curtain from "@/components/curtain";
import NoiseOverlay from "@/components/noise-overlay";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable} h-full antialiased`}
    >

      <body className="min-h-full flex flex-col">
        <TransitionProvider>
          <Curtain />
          <SplashScreen />
          <Navbar />
          {children}
          <NoiseOverlay />
        </TransitionProvider>
      </body>
    </html>
  );
}
